name: Use Docker Image from GHCR

on:
  push:
    branches:
      - main

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          # password: ${{ secrets.MY_PAT }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull and run the Docker image
        run: |
          docker pull ghcr.io/ttshrk/ghcr-sample:latest
